wget http://www.fatihakkus.com/yazane/skinimages/button_10.png
wget http://www.fatihakkus.com/yazane/skinimages/button_10__o.png
wget http://www.fatihakkus.com/yazane/skinimages/button_11.png
wget http://www.fatihakkus.com/yazane/skinimages/button_12.png
wget http://www.fatihakkus.com/yazane/skinimages/button_16.png
wget http://www.fatihakkus.com/yazane/skinimages/button_16__o.png
wget http://www.fatihakkus.com/yazane/skinimages/button_2.png
wget http://www.fatihakkus.com/yazane/skinimages/button_21.png
wget http://www.fatihakkus.com/yazane/skinimages/button_4.png
wget http://www.fatihakkus.com/yazane/skinimages/button_5.png
wget http://www.fatihakkus.com/yazane/skinimages/button_6.png
wget http://www.fatihakkus.com/yazane/skinimages/button_7.png
wget http://www.fatihakkus.com/yazane/skinimages/button_8.png
wget http://www.fatihakkus.com/yazane/skinimages/button_9.png
wget http://www.fatihakkus.com/yazane/skinimages/image_1.png
wget http://www.fatihakkus.com/yazane/skinimages/image_13.png
wget http://www.fatihakkus.com/yazane/skinimages/image_17.png
wget http://www.fatihakkus.com/yazane/skinimages/image_19.png
wget http://www.fatihakkus.com/yazane/skinimages/image_3.png
